{% set name = "metatensor-learn" %}
{% set version = "0.3.2" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/metatensor_learn-{{ version }}.tar.gz
  sha256: 987f63228888882a6189137ddb89f913b2fde1072c3caa83a39b9f5d50388b51

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68
    - packaging >=23
    - pip
  run:
    - python >={{ python_min }}
    - python-metatensor-operations >=0.3.0,<0.4.0

test:
  imports:
    - metatensor
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/metatensor/metatensor
  summary: Building blocks for the atomistic machine learning models based on PyTorch and NumPy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://docs.metatensor.org

extra:
  recipe-maintainers:
    - PicoCentauri
    - Luthaf
